name: tests
on: 
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
jobs:
    run_style_check:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash -l {0}
        steps:
          - uses: actions/checkout@v2
          - uses: conda-incubator/setup-miniconda@v2
            with:
              activate-environment: swe4s
              environment-file: env.yml
          - run: pycodestyle $(git ls-files "*.py")
    
    run_unit_tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: conda-incubator/setup-miniconda@v2
            with:
                activate-environment: swe4s
                environment-file: env.yml
          - run: |
             cd test/unit
             python -m unittest test_my_utils

    run_functional_print_fires:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: conda-incubator/setup-miniconda@v2
            with:
                activate-environment: swe4s
                environment-file: env.yml
          - run: |
             cd test/functional
             bash test_print_fires.sh

    run_functional_plot_hist:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: conda-incubator/setup-miniconda@v2
            with:
                activate-environment: swe4s
                environment-file: env.yml
          - run: |
             python -m pip install -U matplotlib
             cd test/functional
             bash test_plot_hist.sh
